CREATE TABLE passwords_hashes (
    id BIGSERIAL PRIMARY KEY,
    password VARCHAR(255) NOT NULL UNIQUE,
    md5_hash VARCHAR(32) NOT NULL UNIQUE,
    sha1_hash VARCHAR(40) NOT NULL UNIQUE,
    sha256_hash VARCHAR(64) NOT NULL UNIQUE,
    sha512_hash VARCHAR(128) NOT NULL UNIQUE
);